feat: only release hasura after main app has finished
Runn-Fast/deploy-to-heroku-action pull request #87
Opened 2021-07-22 05:16 UTC by stayradiated

2021-07-23 05:52 UTC, ro-savage requested changes

2021-07-23 05:52 UTC, ro-savage commented on src/index.ts
> +        restartIfAlreadyRunning: false,
I thought we deliberately restarted hasura? Because the review app was causing issues, and we needed to reboot hasura to get it working?

@stayradiated

2021-07-23 05:53 UTC, ro-savage commented on src/index.ts
> +        restartIfAlreadyRunning: false,
Although it looks like the review app for this change deployed correctly?

2021-07-23 08:32 UTC, ro-savage approved these changes
Looks good. I tried on a review app, it appeared to do 2 restarts and it also seemed to wait longer before dropping the original dyno.

Although it's hard to tell. Regardless I think this is a nice imporvement.

Thanks for updating this :)

2021-07-26 20:40 UTC, stayradiated commented on src/index.ts
> +        restartIfAlreadyRunning: false,
I had to add in the forced restart when we were doing:

- 1. Deploy hasura
- 2. Migrate DB
- 3. Restart hasura

But now we just do:

-1. Migrate DB
- 2. Deploy hasura

2021-07-26 20:41 UTC, merged